services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend-sf
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    environment:
      - PORT=${BACKEND_PORT}
      - NODE_ENV=production
    depends_on:
      - postgres
  
  frontend:
    build:
      context: ./frontend 
      dockerfile: Dockerfile
    container_name: frontend-sf
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - NODE_ENV=production
  
  postgres:
    image: postgres:13
    container_name: postgres-sf
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data: